### ISSUE TITLE
TTree details -> Getting data into NumPy or Pandas ->missing awkward-pandas

### ISSUE THREAD

**Issue by JacekHoleczek** [hsf-training/hsf-training-scikit-hep-webpage#49]
In the "[`TTree details`](https://hsf-training.github.io/hsf-training-scikit-hep-webpage/03-ttree-details/index.html)" chapter, in the "`Getting data into NumPy or Pandas`" section, there is this line:

`tree.arrays(library="pd", entry_stop=10000)`

It generates:

```
(...)
ModuleNotFoundError: No module named 'awkward_pandas'
(...)
ModuleNotFoundError: install the 'awkward-pandas' package with:
    pip install awkward-pandas # not on conda-forge yet
```

Indeed, when I try to install `awkward-pandas`, I get:

```
(...)
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ awkward-pandas does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs
```

**Comment by klieret** [comment]
Thanks for reaching out! Could you add information about the system that you are using and how you installed the software?

**Comment by jpivarski** [comment]
The tutorial was written before Uproot started requiring the [awkward-pandas](https://github.com/intake/awkward-pandas) package for ragged/non-trivial data in Pandas. The output is different, too, as it no longer "explodes" ragged data into a DataFrame that requires a MultiIndex; it puts the whole Awkward Array into a Pandas Series (column). Specifically, this is a difference between Uproot 4 (2020‒2022) and Uproot 5 (2023‒).

You're right that [awkward-pandas](https://github.com/intake/awkward-pandas) doesn't have a conda package yet; I'll ask @douglasdavis about making one. What I do in this situation is `pip install awkward-pandas` in the activated conda environment. I try to keep pip-installed packages at a minimum in conda environments (since they don't share dependency trees), but if most of my packages are conda and just a few are pip, it's manageable.

In general, you're showing that this tutorial needs an overhaul. We were just talking about that two weeks ago.

**Comment by JacekHoleczek** [comment]
It seems the missing `awkward-pandas ` package was added to the conda-forge, so maybe one should change the message:

`pip install awkward-pandas # not on conda-forge yet`

into something like:

`conda install awkward-pandas`

**Comment by JacekHoleczek** [comment]
This issue has been solved by: [fix: get package import messages up-to-date](https://github.com/scikit-hep/uproot5/pull/947)
